export const schemes = [
  {
    name: "PM-KISAN",
    slug: "pm-kisan",
    description: "Income support of ₹6,000 per year to eligible landholding farmer families.",
    eligibility: ["Landholding farmer family", "As per PM-KISAN exclusion criteria"],
    benefits: ["₹2,000 installments three times a year"],
    requiredDocuments: ["Aadhaar", "Land records", "Bank account"],
    applicationProcess: ["Register on pmkisan.gov.in", "Complete eKYC", "Track installment status"],
    category: "agriculture",
    states: ["ALL"],
    targetGroups: ["farmer"],
    officialUrl: "https://pmkisan.gov.in/",
    sourceRef: "Ministry of Agriculture",
  },
  {
    name: "National Scholarship Portal (NSP)",
    slug: "nsp-scholarships",
    description: "Central and state scholarships for school and higher education students.",
    eligibility: ["Students meeting scheme-specific criteria", "Valid educational enrollment"],
    benefits: ["Tuition / maintenance support depending on scheme"],
    requiredDocuments: ["Aadhaar", "Income certificate", "Marksheets", "Bank details"],
    applicationProcess: ["Create NSP account", "Select scholarship", "Upload documents", "Institute verification"],
    category: "education",
    states: ["ALL"],
    targetGroups: ["student"],
    officialUrl: "https://scholarships.gov.in/",
    sourceRef: "Ministry of Education",
  },
  {
    name: "Ayushman Bharat — PM-JAY",
    slug: "pm-jay",
    description: "Health coverage for eligible poor and vulnerable families for secondary and tertiary care.",
    eligibility: ["Eligible SECC / state listed families"],
    benefits: ["Hospitalization coverage up to scheme limits"],
    requiredDocuments: ["Aadhaar", "Ration / eligibility letter"],
    applicationProcess: ["Check eligibility on pmjay.gov.in", "Visit empanelled hospital", "Use ABHA where applicable"],
    category: "health",
    states: ["ALL"],
    targetGroups: ["senior", "woman", "rural"],
    officialUrl: "https://pmjay.gov.in/",
    sourceRef: "NHA",
  },
  {
    name: "Stand-Up India",
    slug: "stand-up-india",
    description: "Bank loans for SC/ST and women entrepreneurs to start greenfield enterprises.",
    eligibility: ["SC/ST and/or woman entrepreneur", "Greenfield enterprise"],
    benefits: ["Bank loan from ₹10 lakh to ₹1 crore"],
    requiredDocuments: ["Identity & address proofs", "Project report", "Caste certificate if applicable"],
    applicationProcess: ["Apply via standupmitra.in", "Approach bank", "Complete due diligence"],
    category: "entrepreneurship",
    states: ["ALL"],
    targetGroups: ["entrepreneur", "woman"],
    officialUrl: "https://www.standupmitra.in/",
    sourceRef: "DFS / SIDBI",
  },
  {
    name: "PM SVANidhi",
    slug: "pm-svanidhi",
    description: "Micro-credit support for street vendors.",
    eligibility: ["Street vendors", "Urban local body coverage"],
    benefits: ["Working capital loan with incentives for digital repayment"],
    requiredDocuments: ["Vendor certificate / LOI", "Aadhaar", "Bank account"],
    applicationProcess: ["Apply via PMSVANidhi portal", "ULB verification", "Bank disbursal"],
    category: "livelihood",
    states: ["ALL"],
    targetGroups: ["entrepreneur", "urban"],
    officialUrl: "https://pmsvanidhi.mohua.gov.in/",
    sourceRef: "MoHUA",
  },
  {
    name: "Gujarat Vayoshri / Senior Support (illustrative)",
    slug: "gujarat-senior-assistive",
    description: "State-level assistive aids and senior support navigation entry (illustrative seed for demo).",
    eligibility: ["Senior citizens of Gujarat", "As per state scheme norms"],
    benefits: ["Assistive devices / counselling pathways"],
    requiredDocuments: ["Aadhaar", "Age proof", "Residence proof"],
    applicationProcess: ["Contact district social welfare office", "Submit application", "Verification"],
    category: "social-welfare",
    states: ["Gujarat"],
    targetGroups: ["senior"],
    officialUrl: "https://www.india.gov.in/",
    sourceRef: "State Social Welfare (seed)",
  },
];

export const opportunities = [
  {
    title: "Smart India Hackathon",
    type: "hackathon",
    description: "National hackathon for students solving real problem statements.",
    eligibility: ["Student teams from recognized institutions"],
    url: "https://www.sih.gov.in/",
    targetGroups: ["student"],
    states: ["ALL"],
  },
  {
    title: "MyScheme Discovery",
    type: "grant",
    description: "Explore central and state schemes matched to your profile.",
    eligibility: ["Indian citizens"],
    url: "https://www.myscheme.gov.in/",
    targetGroups: ["student", "farmer", "entrepreneur", "woman", "senior"],
    states: ["ALL"],
  },
  {
    title: "NCS Job Portal",
    type: "job",
    description: "National Career Service job listings and counselling.",
    eligibility: ["Job seekers"],
    url: "https://www.ncs.gov.in/",
    targetGroups: ["student", "jobseeker"],
    states: ["ALL"],
  },
  {
    title: "Startup India Hub",
    type: "incubator",
    description: "Startup recognition, benefits, and incubator discovery.",
    eligibility: ["DPIIT-eligible startups"],
    url: "https://www.startupindia.gov.in/",
    targetGroups: ["entrepreneur"],
    states: ["ALL"],
  },
  {
    title: "AICTE Internship Portal",
    type: "internship",
    description: "Internships for technical education students.",
    eligibility: ["Enrolled students"],
    url: "https://internship.aicte-india.org/",
    targetGroups: ["student"],
    states: ["ALL"],
  },
];

export default { schemes, opportunities };
